### ISSUE TITLE
PostgreSQL driver should not be hard-coded to public schema

### ISSUE THREAD

**Issue by Watkinsong** [Codeception/module-db#15]
#### What are you trying to achieve?
In src/Codeception/Lib/Driver/PostgreSql.php, the schema is hard-coded to "public" in method cleanup. In my setup, where the schema used for testing is not public, this causes tests to fail with a ModuleException:
` [ModuleException] Db: SQLSTATE[42501]: Insufficient privilege: 7 ERROR:  must be owner of schema public`
The schema is taken into account in "load" method, and this should also be brought into cleaning up the test database.

### Details

* Codeception version: 2.3.7
* PHP Version: 7.0.22
* Operating System: Ubuntu
* Installation type: Phar
* List of installed packages (`composer show`)

**Comment by rija** [comment]
I just ran into that error. The workaround is to also use the ``populator`` property which is the recommendation in the documentation anyway:
```
    - Db:
        dsn: 'pgsql:host=dbserver;dbname=mydb;port=5432'
        user: 'myuser'
        password: 'somepassword'
        dump: 'sql/mydb_tables.sql'
        poplulate: true
        clean: true
        populator: 'psql -h $host -U $user --clean --create --dbname $dbname -f $dump'
```
